# version: '3.8'

services:
  sec_app:
    build:
      context: ./crud-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  crud_app:
    build:
      context: ./crud-app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
