# =========================== # 
# === Production Pipeline === # 
# =========================== # 
name: Production 

# + Trigger {{{
on: 
  push: 
    branches: 
      - main
# }}}
# + Steps {{{
jobs: 
  build-and-deploy: 
    runs-on: ubuntu:latest

    steps: 
      # Move The Project To VPS 
      - name: Checkout code 
        uses: actions/checkout@v2

      # Move .env File To Dir 
      - name: Move .env File to Seucrity 
        run: cp /home/ubuntu/env ./security-app/.env 

      # Build The Project 
      - name: Auto Run 
        run: docker compose up --build -d 
# }}}
